version: '3.3'

services:
  postgres:
    container_name: flora-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: flora-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
